project:
  type: website
  output-dir: docs

website:
  title: "Nusret Ozates"
  site-url: https://nusretozates.github.io/
  description: "Welcome to Nusret Ozates's personal website. Explore my projects, blogs, and more!"
  navbar:
    background: dark
    right:
      - icon: github
        href: https://github.com/NusretOzates
      - icon: twitter
        href: https://twitter.com
    left:
      - text: Blogs
        href: myposts.qmd

format:
  html:
    respect-user-color-scheme: true
    smooth-scroll: true
    theme:
      light: zephyr
      dark: darkly
    css: styles.css
    include-in-header:
      - text: |
         <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/>
# mainfont: Roboto


