project:
  type: website
  output-dir: docs

website:
  title: "Nusret Ozates's Blog"
  navbar:
    background: dark
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/NusretOzates
      - icon: twitter
        href: https://twitter.com
    left:
      - text: Blogs
        href: myposts.qmd

format:
  html:
    respect-user-color-scheme: true
    smooth-scroll: true
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    include-in-header:
      - text: |
         <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/>
mainfont: Roboto


